# Generated by Django 3.0.5 on 2020-05-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200527_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
    ]
