# Generated by Django 3.0.5 on 2020-05-27 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20200527_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='IsVideo',
        ),
    ]
