# Generated by Django 3.0.5 on 2020-05-27 18:25

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_remove_post_isvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
