# Generated by Django 3.0.5 on 2020-08-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mains',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
